meta_product_name: "Sobrou App"
meta_title: "Sobrou App - Mude seu consumo. Mude seu mundo."
meta_description: "Um marketplace para você evitar o desperdício, matar sua fome e ajudar o mundo. Como cliente, compre mais barato e ajude a evitar o desperdício. Se você tem um restaurante, ganhe dinheiro com o que você jogaria fora."
meta_image: "sobrou_og.png"
